SET NAMES utf8mb4;
INSERT INTO portales_prensa (Nombre, Url, Region, PartidoId) VALUES
('0221',                  'https://www.0221.com.ar/',               'AMBA / Provinciales', 55),
('El Dia',                'https://www.eldia.com/',                  'AMBA / Provinciales', 55),
('Infocielo',             'https://infocielo.com/',                  'AMBA / Provinciales', NULL),
('Data Judicial',         'https://datajudicial.com.ar/',            'AMBA / Provinciales', NULL),
('Diario Conurbano',      'https://diarioconurbano.com.ar/',         'AMBA / Provinciales', NULL),
('Online 911',            'https://www.online-911.com/',             'AMBA / Provinciales', NULL),
('Diario NCO',            'https://diario-nco.net/',                 'La Matanza',          49),
('El1 Digital',           'https://www.el1digital.com.ar/',          'La Matanza',          49),
('Diario Conurbano',      'https://diarioconurbano.com.ar/',         'Lomas de Zamora',     69),
('La Union',              'https://launion.com.ar/',                 'Lomas de Zamora',     69),
('Perspectiva Sur',       'https://perspectivasur.com/',             'Quilmes',             104),
('El Sol Noticias',       'https://elsolnoticias.com.ar/',           'Quilmes',             104),
('Infosur Diario',        'https://infosurdiario.com.ar/',           'Florencio Varela',    103),
('Berazategui Noticias',  'https://berazategui.info/',               'Berazategui',         102),
('Lanus Noticias',        'https://lanusnoticias.com.ar/',           'Lanus',               68),
('Politica del Sur',      'https://politicadelsur.com/',             'Avellaneda',          65),
('Primer Plano Online',   'https://primerplanoonline.com.ar/',       'Moron / Oeste',       88),
('Desalambrar',           'https://desalambrar.com.ar/',             'Moreno',              40),
('Merlo GBA',             'https://merlogba.com/',                   'Merlo',               87),
('Oeste Noticias',        'https://oestenoticias.com/',              'Ituzaingo',           86),
('Hurlingham Post',       'https://hurlinghampost.com/',             'Hurlingham',          85),
('SM Noticias',           'https://smnoticias.com/',                 'San Martin',          111),
('Que Pasa Web',          'https://www.quepasaweb.com.ar/',          'Tres de Febrero',     113),
('Aqui La Noticia',       'https://aquilanoticia.com/',              'San Miguel',          112),
('Semanario Actualidad',  'https://semanarioactualidad.com.ar/',     'Jose C. Paz',         109),
('Tiempo de Tortuguitas', 'https://tiempodetortuguitas.com.ar/',     'Malvinas Argentinas', 110),
('Pilar a Diario',        'https://pilardiario.com/',                'Pilar',               96),
('El Dia de Escobar',     'https://eldiadeescobar.com.ar/',          'Escobar',             134),
('Tigre al Dia',          'https://tigrealdia.com.ar/',              'Tigre',               107),
('Zona Norte Diario',     'https://www.zonanortediario.com.ar/',     'San Isidro',          106),
('Vicente Lopez Hoy',     'https://vicentelopezhoy.com/',            'Vicente Lopez',       108),
('Campana Noticias',      'https://campananoticias.com/',            'Campana',             133),
('Enlace Critico',        'https://www.enlacecritico.com/',          'Zarate',              135),
('La Union Digital',      'https://launion.com.ar/',                 'Ezeiza',              67),
('El Diario Sur',         'https://eldiariosur.com/',                'Esteban Echeverria',  66),
('0223',                  'https://www.0223.com.ar/',                'Mar del Plata',       72),
('La Capital',            'https://www.lacapitalmdp.com/',           'Mar del Plata',       72),
('Ahora Mar del Plata',   'https://ahoramardelplata.com.ar/',        'Mar del Plata',       72),
('Que Digital',           'https://quedigital.com.ar/',              'Mar del Plata',       72),
('Costa de Noticias',     'https://costadenoticias.com/',            'Partido de La Costa', 99),
('Opinion de La Costa',   'https://opiniondelacosta.com.ar/',        'Partido de La Costa', 99),
('Minuto G',              'https://www.minutog.com/',                'Villa Gesell',        101),
('Pinamar Diario',        'https://pinamardiario.com/',              'Pinamar',             100),
('TSN Necochea',          'https://www.tsnnecochea.com.ar/',         'Necochea',            90),
('Cuatro Vientos',        'https://www.diario4v.com/',               'Necochea',            90),
('La Nueva',              'https://www.lanueva.com/',                'Bahia Blanca',        14),
('BHInfo',                'https://www.bhinfo.com.ar/',              'Bahia Blanca',        14),
('El Eco',                'https://www.eleco.com.ar/',               'Tandil',              11),
('ABCHoy',                'https://www.abchoy.com.ar/',              'Tandil',              11),
('Central de Noticias',   'https://cdnoticias.com/',                 'Olavarria',           9),
('Infoeme',               'https://www.infoeme.com/',                'Olavarria',           9),
('El Tiempo',             'https://www.diarioeltiempo.com.ar/',      'Azul',                2),
('La Voz del Pueblo',     'https://lavozdelpueblo.com.ar/',          'Tres Arroyos',        24),
('Democracia',            'https://www.diariodemocracia.com/',       'Junin',               45),
('Junin 24',              'https://junin24.com/',                    'Junin',               45),
('La Opinion',            'https://laopinionline.ar/',               'Pergamino',           93),
('Diario El Norte',       'https://diarioelnorte.com.ar/',           'San Nicolas',         118),
('La Razon',              'https://www.larazondechivilcoy.com.ar/',  'Chivilcoy',           79),
('Noticias Mercedinas',   'https://noticiasmercedinas.com/',         'Mercedes',            80),
('La Manana',             'https://www.diariolamanana.com.ar/',      'Bolivar',             4),
('Noticias Pehuajo',      'https://noticiaspehuajo.com/',            'Pehuajo',             127);
